<a href="https://colab.research.google.com/github/KingGuy123/ML-Practice/blob/main/Pandas_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [31]:
df = pd.DataFrame([[1,2,3],[4,5,6], [7,8,9]], columns = ["A", "B", "C"], index= ["D", "E", "F"])

df.head() shows first 5 rows by default, can also take arguments

In [32]:
df.head()

   A  B  C
D  1  2  3
E  4  5  6
F  7  8  9

We can see giving 2 as an argument to head() function now displays 2 rows only.

In [33]:
df.head(2)

   A  B  C
D  1  2  3
E  4  5  6

df.tail() shows bottom 5 rows by default and can also take arguments.

In [34]:
df.tail()

   A  B  C
D  1  2  3
E  4  5  6
F  7  8  9

Giving tail() an argument of 1 shows the bottom row of the data or array set.

In [35]:
df.tail(1)

   A  B  C
F  7  8  9

df.columns shows the column names as specified or just [1,2,3] by default.

In [36]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

df directly displays the whole array at once.

In [37]:
df

   A  B  C
D  1  2  3
E  4  5  6
F  7  8  9

df.index shows the row namings or [1,2,3] by default.

In [38]:
df.index

Index(['D', 'E', 'F'], dtype='object')

Displays the index as a list

In [39]:
df.index.tolist()

['D', 'E', 'F']

Displays columns as a list

In [40]:
df.columns.tolist()

['A', 'B', 'C']

Displays information about all the rows

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, D to F
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0+ bytes

Gives information about all the numbers in the column

In [42]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0