<a href="https://colab.research.google.com/github/KingGuy123/ML-Practice/blob/main/Pandas_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**References: https://github.com/KeithGalli/complete-pandas-tutorial/tree/master**

In [68]:
import pandas as pd

In [31]:
df = pd.DataFrame([[1,2,3],[4,5,6], [7,8,9]], columns = ["A", "B", "C"], index= ["D", "E", "F"])

df.head() shows first 5 rows by default, can also take arguments

In [32]:
df.head()

   A  B  C
D  1  2  3
E  4  5  6
F  7  8  9

We can see giving 2 as an argument to head() function now displays 2 rows only.

In [33]:
df.head(2)

   A  B  C
D  1  2  3
E  4  5  6

df.tail() shows bottom 5 rows by default and can also take arguments.

In [34]:
df.tail()

   A  B  C
D  1  2  3
E  4  5  6
F  7  8  9

Giving tail() an argument of 1 shows the bottom row of the data or array set.

In [35]:
df.tail(1)

   A  B  C
F  7  8  9

df.columns shows the column names as specified or just [1,2,3] by default.

In [36]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

df directly displays the whole array at once.

In [37]:
df

   A  B  C
D  1  2  3
E  4  5  6
F  7  8  9

df.index shows the row namings or [1,2,3] by default.

In [38]:
df.index

Index(['D', 'E', 'F'], dtype='object')

Displays the index as a list

In [39]:
df.index.tolist()

['D', 'E', 'F']

Displays columns as a list

In [40]:
df.columns.tolist()

['A', 'B', 'C']

Displays information about all the rows

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, D to F
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0+ bytes

Gives information about all the numbers in the column

In [42]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

How many unique values are in a column

In [47]:
df.nunique()

A    3
B    3
C    3
dtype: int64

Find specifically for A column

In [50]:
df["A"].unique()

array([1, 4, 7])

Gives the size of the dataframe

In [52]:
df.shape

(3, 3)

Number of cells in the dataframe

In [54]:
df.size

9

To get data from a folder ont he desktop

In [55]:
#pd.read_csv('./foldercoffee.csv')

To get data from a raw file from GitHub

In [57]:
coffee = pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv')

Tested out all the previous functions on the new dataframe.

In [58]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [59]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [60]:
coffee.tail()

         Day Coffee Type  Units Sold
9     Friday       Latte          35
10  Saturday    Espresso          45
11  Saturday       Latte          35
12    Sunday    Espresso          45
13    Sunday       Latte          35

In [62]:
coffee.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Day          14 non-null     object
 1   Coffee Type  14 non-null     object
 2   Units Sold   14 non-null     int64
dtypes: int64(1), object(2)
memory usage: 468.0+ bytes

In [63]:
coffee.describe()

       Units Sold
count   14.000000
mean    32.857143
std      9.346798
min     15.000000
25%     26.250000
50%     35.000000
75%     38.750000
max     45.000000

In [64]:
coffee.index

RangeIndex(start=0, stop=14, step=1)

In [65]:
coffee.columns

Index(['Day', 'Coffee Type', 'Units Sold'], dtype='object')

**Multiple different extensions are used other than csv. Feather and Parquet are also used which store the same data in relatively smaller size.**

In [67]:
results = pd.read_parquet('results.parquet')

In [ ]:
olymp_data = pd.read_excel('olympics-data.xlsx')