<a href="https://colab.research.google.com/github/KingGuy123/ML-Practice/blob/main/Pandas_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [13]:
df = pd.DataFrame([[1,2,3],[4,5,6], [7,8,9]], columns = ["A", "B", "C"], index= ["A", "B", "C"])

df.head() shows first 5 rows by default, can also take arguments

In [16]:
df.head()

   A  B  C
A  1  2  3
B  4  5  6
C  7  8  9

We can see giving 2 as an argument to head() function now displays 2 rows only.

In [18]:
df.head(2)

   A  B  C
A  1  2  3
B  4  5  6

df.tail() shows bottom 5 rows by default and can also take arguments.

In [19]:
df.tail()

   A  B  C
A  1  2  3
B  4  5  6
C  7  8  9

Giving tail() an argument of 1 shows the bottom row of the data or array set.

In [20]:
df.tail(1)

   A  B  C
C  7  8  9